# Formality comparison for Raven SoC
# Reference: synthesis-compatible RTL
# Implementation: Design Compiler synthesized gate-level netlist

set DESIGN raven_soc

set REPORT_DIR formality/reports
file mkdir $REPORT_DIR

# Standard-cell library must be supplied externally.
# No PDK or standard-cell library files are included in this repository.
if {![info exists ::env(RAVEN_TARGET_DB)]} {
    error "Set RAVEN_TARGET_DB to the path of the standard-cell .db library used for synthesis."
}
set TARGET_DB $::env(RAVEN_TARGET_DB)

# Search paths for the synthesis RTL, shared Raven/PicoRV32 RTL,
# and Design Compiler generated outputs.
set search_path [list . rtl ../simulation/raven_soc outputs]

set synopsys_auto_setup true

# Read Formality guidance generated by Design Compiler.
# This must be done before reading the designs.
set_svf outputs/${DESIGN}.svf

# Read reference RTL
read_verilog -container r -libname WORK rtl/raven_soc_dc.v
set_top r:/WORK/$DESIGN

# Load the externally supplied standard-cell library so Formality
# can interpret the mapped implementation cells.
read_db -container i $TARGET_DB

# Read implementation gate-level netlist generated by Design Compiler
read_verilog -container i -libname WORK -netlist outputs/${DESIGN}_synth.v
set_top i:/WORK/$DESIGN

# Match reference and implementation points
match

# Verify equivalence
verify

# Generate reports
report_matched_points > $REPORT_DIR/${DESIGN}_matched_points.rpt
report_unmatched_points > $REPORT_DIR/${DESIGN}_unmatched_points.rpt
report_failing_points > $REPORT_DIR/${DESIGN}_failing_points.rpt
report_passing_points > $REPORT_DIR/${DESIGN}_passing_points.rpt

exit
